patches_dir = "patches"

[patches.emoji-reactions]
mode = "patch"
# Own patch rebased onto glitch-soc's main branch, since
# the version GitHub produces doesn't apply cleanly.
url = "https://paste.gmem.ca/paste/0e0e6534-2bef-442f-8d73-5aff2a3514b4/raw"
name = "0001-emoji-reactions.patch"

[patches.redis-sentinel]
mode = "diff"
url = "https://patch-diff.githubusercontent.com/raw/mastodon/mastodon/pull/26571.diff"
name = "0002-redis-sentinel.diff"
