name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - uses: taiki-e/install-action@just

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run build
      run: |
        echo "Checking patches against glitch-soc $(cat .current)"
        just build-mastodon
