name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - uses: taiki-e/install-action@just

    - name: Run build
      run: just build
