name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - uses: taiki-e/install-action@just

    - name: Log in to the Container registry
      uses: docker/login-action@3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run build
      run: just build

    - name: Push images
      run: just push-docker
