name: Check that patches apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - uses: taiki-e/install-action@just

    - name: Run build
      run: |
        echo "Checking patches against glitch-soc $(cat .current)"
        just build-mastodon
